### ISSUE TITLE
Update Packages

### ISSUE THREAD

**Issue by IrreverentMrB** [danielimmke/pardot-starter#1]
Gulp-util has been deprecated, I get a link to the following page when tryin to install https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by danielimmke** [comment]
It is deprecated, but you can still use this starterpack- just tested it. You're welcome to open a PR with updated NPM packages if you go through and update them.

**Comment by danielimmke** [comment]
This project could use a little love. Could use somebody to go in and update all the packages and confirm that it still works.

**Comment by danielimmke** [comment]
All of the packages have been updated and the Gulpfile has been refactored to use the new Gulp 4 API. This should resolve any issues.
